spring:
  application:
    name: task-manager
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.yourapp.taskmanager: DEBUG




